Kafka:
  acks: 'all'
  producerId: 'transaction_producer'
  bootstrapServersHost: 'localhost'
  bootstrapServersPort: '9092'
  autoOffsetReset: 'smallest'
  groupId: 'transaction_consumer'

Encryption:
  algorithm: 'AES'
  encryptionKey: 'N1PCdw3M2B1TfJhoaY2mL736p2vCUc47'

ProducerServer:
  bindAddr: '0.0.0.0:8000'
  readTimeout: '10'
  writeTimeout: '10'
  idleTimeout: '5'

ClientServer:
  bindAddr: '0.0.0.0:5000'
  readTimeout: '10'
  writeTimeout: '10'
  idleTimeout: '5'

PostgresDB:
  user: 'postgres'
  password: 'password'
  host: 'localhost'
  port: '5432'
  dbname: 'authentication'
  sslmode: 'disable'
  maxconns: '30'

Authentication:
  jwtSecretKey: 'secretjwtkey'