Kafka:
  acks: 'all'
  producerId: 'transaction_producer'
  bootstrapServersHost: 'localhost'
  bootstrapServersPort: '9092'
  autoOffsetReset: 'smallest'

Encryption:
  algorithm: 'AES'
  encryptionKey: 'thisis32bitlongpassphraseimusing'